export const NEST_COUCH_OPTIONS = 'NEST_COUCH_OPTIONS';
export const NEST_COUCH_CONNECTION = 'NEST_COUCH_CONNECTION';
export const NEST_COUCH_DEFAULT_BUCKET = 'NEST_COUCH_DEFAULT_BUCKET';
export const NEST_COUCH_BUCKETS = 'NEST_COUCH_BUCKETS';
